version: 2.1

orbs:
  docker: circleci/docker@2.5.0

commands:
  check_dir_changed:
    description: |
      Check if the directory is changed 
    parameters:
      DIR_TO_CHECK:
        type: string
    steps:
      - checkout
      - run:
          name: Check dir changed
          command: |
            ls -la
            REF=HEAD
            SINCE=origin/main
            DIR_TO_CHECK=<<parameters.DIR_TO_CHECK>>

            MERGE_BASE=$(git merge-base ${SINCE} ${REF})
            echo $MERGE_BASE
            FILES_CHANGED=$(git diff --name-only ${MERGE_BASE}..${REF} -- ${DIR_TO_CHECK})
            printf "Files changed:\n${FILES_CHANGED}\n"

            if [[ -n $FILES_CHANGED ]]; then
              echo "Found changes !!! ... setting var to true"
              echo 'export IS_CHANGED='"true" >> "$BASH_ENV"
            else
              echo "No changes Found!!! ... setting var to false"
              echo 'export IS_CHANGED='"false" >> "$BASH_ENV"
            fi

jobs:
  job_for_svc_1:
    parameters:
      flag_checking_dir_change:
        type: env_var_name
        default: IS_CHANGED
    executor: docker/docker
    steps:
      - check_dir_changed:
          DIR_TO_CHECK: svc-1
      - when:
          condition: $IS_CHANGED
          steps:
            - run : echo "Changes found ... executing this job"

  
  job_for_svc_2:
    parameters:
      flag_checking_dir_change:
        type: env_var_name
        default: IS_CHANGED
    executor: docker/docker
    steps:
      - check_dir_changed:
          DIR_TO_CHECK: svc-2
      - when:
          condition: $IS_CHANGED
          steps:
            - run: echo $IS_CHANGED
            - run : echo "Changes found ... executing this job"

workflows:
  svc_1_workflow:
    jobs:
      - job_for_svc_1
  svc_2_workflow:
    jobs:
      - job_for_svc_2